---
title: 
    "Применение технологий искусственного интеллекта и машинного обучения для поиска угроз информационной безопасности"
author: "Kabanova Svetlana"
format: 
    md:
        output-file: README.md
editor: visual
---

# Лабораторная работа №4

Анализ данных сетевого трафика с использованием аналитической in-memory СУБД DuckDB

## Цель работы

1\.  Изучить возможности СУБД DuckDB для обработки и анализ больших данных.

2\.  Получить навыки применения DuckDB совместно с языком программирования R.

3\.  Получить навыки анализа метаинфомации о сетевом трафике.

4\.  Получить навыки применения облачных технологий хранения, подготовки и анализа данных: Yandex Object Storage, Rstudio Server.


## Задание

Используя язык программирования R, СУБД и пакет duckdb и облачную IDE Rstudio Server, развернутую в Yandex Cloud, выполнить задания и составить отчет.

```{r}
install.packages("dplyr") 
library(dplyr)
```


## Ход работы


### Задание 1: Надите утечку данных из Вашей сети



### Задание 2: Надите утечку данных 2


### Задание 3: Надите утечку данных 3

### Задание 4: Обнаружение канала управления

### Задание 5: Обнаружение P2P трафика

### Задание 6: Чемпион малвари


## Оценка результата


## Вывод
